name: OSINT Bot Monitoring

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_notification:
        description: 'Force notification even if bot is healthy'
        required: false
        default: 'false'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot==13.15
          
      - name: Run bot health check
        id: health_check
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
        run: |
          python .github/scripts/monitor_bot.py
        continue-on-error: true
          
      - name: Send notification if bot is down
        if: ${{ steps.health_check.outcome == 'failure' || github.event.inputs.force_notification == 'true' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚨 *OSINT Bot Alert*
            
            Bot appears to be DOWN or not responding.
            
            Time: ${{ steps.health_check.outputs.timestamp || github.run_started_at }}
            
            Last error: ${{ steps.health_check.outputs.error || 'No response from bot' }}
            
            Check Render dashboard: https://dashboard.render.com/
          
      - name: Update status in repository
        if: always()
        run: |
          mkdir -p .github/status
          if [ "${{ steps.health_check.outcome }}" == "success" ]; then
            echo "Bot is healthy as of $(date -u)" > .github/status/bot_status.txt
            echo "last_check=$(date -u +"%Y-%m-%d %H:%M:%S")" >> .github/status/bot_status.txt
            echo "status=healthy" >> .github/status/bot_status.txt
          else
            echo "Bot is DOWN as of $(date -u)" > .github/status/bot_status.txt
            echo "last_check=$(date -u +"%Y-%m-%d %H:%M:%S")" >> .github/status/bot_status.txt
            echo "status=down" >> .github/status/bot_status.txt
          fi
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .github/status/bot_status.txt
          git commit -m "Update bot status [skip ci]" || echo "No changes to commit"
          git push