# Exported from Render on 2025-07-15T14:51:45Z
services:
- type: worker
  name: osint-bot
  runtime: python
  repo: https://github.com/nyrumx/osint-bot
  plan: starter
  envVars:
  - key: WHOIS_API_KEY
    sync: false
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  region: oregon
  buildCommand: chmod +x start.sh
  startCommand: ./start.sh
  disk:
    name: disk
    mountPath: /data
    sizeGB: 10
  autoDeployTrigger: commit
version: "1"
